language: r
warnings_are_errors: true
sudo: required
cache: packages
r:
  - 3.4
  - release
  - devel

matrix:
  allow_failures:
    - r: release
    - r: devel

r_binary_packages:
  - knitr
  - survival
  - roxygen2
  - varhandle
  - glmnet
  - pROC
  - doParallel
  - foreach
  - graphics

before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release'

