# This is my own action yaml file and it is NOT TESTED. Use at your own risk!

name: R CMD check --as-cran

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [3.5, 3.6]

    steps:
      - uses: actions/checkout@v2
      - name: install R-related dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libgit2-dev
          sudo apt-get install libssh2-1-dev
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Running make - documentation
        run: make clean docs
      - name: Running make - building
        run: make build
      - name: Running make - check with CRAN
        run: make check-cran
