# This is my own action yaml file and it is NOT TESTED. Use at your own risk!

name: R build check (no manual, no vignette, no cran)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [3.5, 3.6]

    steps:
      - uses: actions/checkout@v2
      - name: install R-related dependencies
        run: |
          apt install libcurl4-openssl-dev
          apt install libgit2-dev
          apt install libssh2-1-dev
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Running make - documentation
        run: make clean docs
      - name: Running make - building without manual
        run: make build-noman
      - name: Running make - check without CRAN
        run: make check
